DROP SCHEMA IF EXISTS "TEJASTORE_TEST" CASCADE;
CREATE SCHEMA "TEJASTORE_TEST";
--SET search_path='TEJASTORE';
SET search_path='TEJASTORE_TEST';

DROP TABLE IF EXISTS "TIPO_GASTOS" CASCADE;
CREATE TABLE "TIPO_GASTOS"(
 "ID" SERIAL NOT NULL,
 "NOMBRE" varchar(50),
 PRIMARY KEY("ID"));

DROP TABLE IF EXISTS "GASTOS" CASCADE;
CREATE TABLE "GASTOS"(
 "ID" SERIAL UNIQUE NOT NULL,
 "TIPO_GASTOS_ID" INTEGER,
 "DESCR" varchar(500),
 FOREIGN KEY ("TIPO_GASTOS_ID") REFERENCES "TIPO_GASTOS"("ID"),
 PRIMARY KEY("ID"));

DROP TABLE IF EXISTS "PAIS" CASCADE;
CREATE TABLE "PAIS"(
 "ID" SERIAL NOT NULL,
 "NOMBRE" varchar(50),
PRIMARY KEY("ID"));

DROP TABLE IF EXISTS "PROVINCIA" CASCADE;
CREATE TABLE "PROVINCIA"(
 "ID" SERIAL NOT NULL,
 "NOMBRE" varchar(50),
 "PAIS_ID" integer NOT NULL,
 FOREIGN KEY ("PAIS_ID") REFERENCES "PAIS"("ID"),
PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS  "LOCALIDAD" CASCADE;
CREATE TABLE "LOCALIDAD"(
 "ID" SERIAL NOT NULL,
 "NOMBRE" varchar(50),
 "PROVINCIA_ID" integer NOT NULL,
 FOREIGN KEY ("PROVINCIA_ID") REFERENCES "PROVINCIA" ("ID"),
 PRIMARY KEY ("ID"));


DROP TABLE IF EXISTS "MARCA" CASCADE;
CREATE TABLE "MARCA"(
	"ID" SERIAL UNIQUE NOT NULL,
	"NOMBRE" varchar(50),
	PRIMARY KEY("ID"));


DROP TABLE IF EXISTS "TIPO_ID" CASCADE;

CREATE TABLE "TIPO_ID"(
	"ID" SERIAL UNIQUE NOT NULL,
	"NOMBRE" varchar(50));

DROP TABLE IF EXISTS "ARTICULO" CASCADE;

CREATE TABLE "ARTICULO"(
 "ID" SERIAL UNIQUE NOT NULL,
 "CODIGO" integer,
 "NOMBRE" varchar(50),
 "PRECIO_COMPRA" float,
 "PRECIO_VENTA" float,
 "STOCK_MIN" integer,
 "STOCK_MAX" integer,
 "CANTIDAD" integer,
 "MARCA_ID" integer,
 FOREIGN KEY ("MARCA_ID") REFERENCES "MARCA"("ID"),
 PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS "EMPRESA" CASCADE;

CREATE TABLE "EMPRESA"(
 "ID" SERIAL UNIQUE NOT NULL,
 "NOMBRE" varchar(50),
 "CUIT" varchar(20),
 "CALLE" varchar(50),
 "NRO" integer,
 "PISO" integer,
 "TEL_FIJO" varchar(20),
 "TEL_CEL" varchar(20),
 "EMAIL" varchar(50),
 "DESCR" varchar(500),
 "LOC_ID" integer,
 PRIMARY KEY ("CUIT"),
 FOREIGN KEY ("LOC_ID") REFERENCES "LOCALIDAD"("ID"));

DROP TABLE IF EXISTS "TURNO" CASCADE;
CREATE TABLE "TURNO"(
 "ID" SERIAL UNIQUE NOT NULL,
 "H_ENTRADA" date,
 "H_SALIDA" date,
 PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS "PERSONA" CASCADE;
CREATE TABLE "PERSONA"(
 "ID" SERIAL UNIQUE NOT NULL,
 "TIPO_ID" integer,
 "DNI" varchar(20) NOT NULL,
 "NOMBRE" varchar(100),
 "APELLIDO" varchar(50),
 "CALLE" varchar(50),
 "NRO" integer,
 "PISO" integer,
 "LOC_ID" integer,
 "TEL_FIJO" varchar(20),
 "TEL_CEL" varchar(20),
 "EMAIL" varchar(50),
 "CUIL" varchar(50),
 "FECHA_NACIMIENTO" date,
 FOREIGN KEY ("TIPO_ID") REFERENCES "TIPO_ID"("ID"),
 FOREIGN KEY ("LOC_ID") REFERENCES "LOCALIDAD"("ID"),
 PRIMARY KEY ("DNI"));

DROP TABLE IF EXISTS "GASTOS_PERSONA" CASCADE;
CREATE TABLE "GASTOS_PERSONA" (
 "ID_GASTOS" INTEGER NOT NULL,
 "ID_PERSONA" INTEGER NOT NULL,
 FOREIGN KEY ("ID_GASTOS") REFERENCES "GASTOS"("ID"),
 FOREIGN KEY ("ID_PERSONA") REFERENCES "PERSONA"("ID"),
 PRIMARY KEY("ID_GASTOS","ID_PERSONA"));

DROP TABLE IF EXISTS "TURNO_PERSONA" CASCADE;
CREATE TABLE "TURNO_PERSONA"(
 "TURNO_ID" integer NOT NULL,
 "PERS_ID" integer NOT NULL,
FOREIGN KEY ("TURNO_ID") REFERENCES "TURNO" ("ID"),
FOREIGN KEY ("PERS_ID") REFERENCES "PERSONA" ("ID"),
PRIMARY KEY ("TURNO_ID","PERS_ID"));

DROP TABLE IF EXISTS "EMPLEADO" CASCADE;
CREATE TABLE "EMPLEADO"(
 "ID" integer NOT NULL,
FOREIGN KEY ("ID") REFERENCES "PERSONA" ("ID"),
PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS "GERENTE";
CREATE TABLE "GERENTE"(
 "ID" integer NOT NULL,
FOREIGN KEY ("ID") REFERENCES "PERSONA"("ID"),
PRIMARY KEY ("ID"));


DROP TABLE IF EXISTS "RUBRO" CASCADE;
CREATE TABLE "RUBRO"(
 "ID" SERIAL UNIQUE NOT NULL,
 "NOMBRE" varchar(50),
PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS "EMPRESA_PROVEE" CASCADE;
CREATE TABLE "EMPRESA_PROVEE"(
 "ID_ART" INTEGER NOT NULL,
 "ID_EMP" INTEGER NOT NULL,
FOREIGN KEY ("ID_ART") REFERENCES "ARTICULO" ("ID"),
FOREIGN KEY ("ID_EMP") REFERENCES "EMPRESA" ("ID"),
PRIMARY KEY ("ID_ART","ID_EMP"));

DROP TABLE IF EXISTS "VENTA" CASCADE;
CREATE TABLE "VENTA"(
 "ID" SERIAL UNIQUE NOT NULL,
 "MONTO" integer,
 "HORARIO" timestamp,
 "ID_PERS" integer NOT NULL,
FOREIGN KEY ("ID_PERS") REFERENCES "PERSONA" ("ID"),
PRIMARY KEY ("ID"));

DROP TABLE IF EXISTS "ARTICULO_VENTA" CASCADE;
CREATE TABLE "ARTICULO_VENTA"(
 "ID_ART" integer NOT NULL,
 "ID_VEN" integer NOT NULL,
 "CANT" integer NOT NULL,
FOREIGN KEY ("ID_ART") REFERENCES "ARTICULO" ("ID"),
FOREIGN KEY ("ID_VEN") REFERENCES "VENTA" ("ID"),
PRIMARY KEY ("ID_ART","ID_VEN"));

DROP TABLE IF EXISTS "ARTICULO_RUBRO" CASCADE;

CREATE TABLE "ARTICULO_RUBRO"(
 "ID_ART" integer NOT NULL,
 "ID_RUB" integer NOT NULL,
FOREIGN KEY ("ID_ART") REFERENCES "ARTICULO" ("ID"),
FOREIGN KEY ("ID_RUB") REFERENCES "RUBRO" ("ID"),
PRIMARY KEY ("ID_ART","ID_RUB"));

DROP TABLE IF EXISTS "CONFIG" CASCADE;
CREATE TABLE "CONFIG"(
 "ID" SERIAL UNIQUE NOT NULL,
 "NOMBRE" VARCHAR(50) NOT NULL,
 "CUIT" VARCHAR(20),
 "CALLE" varchar(50),
 "NRO" integer,
 "PISO" integer,
 "LOC_ID" integer,
 "TEL_FIJO" varchar(20),
 "TEL_CEL" varchar(20),
 "EMAIL" varchar(50),
 "LOGO" bytea,
 "IVA" float,
 PRIMARY KEY("ID"));

DROP SEQUENCE IF EXISTS "ARTICULO_CODIGO_SEQ";
CREATE SEQUENCE "ARTICULO_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "ARTICULO_CODIGO_SEQ"
  OWNER TO postgres;


DROP SEQUENCE IF EXISTS "PAIS_CODIGO_SEQ";
CREATE SEQUENCE "PAIS_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "PAIS_CODIGO_SEQ"
  OWNER TO postgres;


DROP SEQUENCE IF EXISTS "PROVINCIA_CODIGO_SEQ";
CREATE SEQUENCE "PROVINCIA_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "PROVINCIA_CODIGO_SEQ"
  OWNER TO postgres;

  
DROP SEQUENCE IF EXISTS "LOCALIDAD_CODIGO_SEQ";
CREATE SEQUENCE "LOCALIDAD_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "LOCALIDAD_CODIGO_SEQ"
  OWNER TO postgres;

  
DROP SEQUENCE IF EXISTS "PERSONA_CODIGO_SEQ";
CREATE SEQUENCE "PERSONA_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "PERSONA_CODIGO_SEQ"
  OWNER TO postgres;


DROP SEQUENCE IF EXISTS "EMPRESA_CODIGO_SEQ";
CREATE SEQUENCE "EMPRESA_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "EMPRESA_CODIGO_SEQ"
  OWNER TO postgres;

  
DROP SEQUENCE IF EXISTS "RUBRO_CODIGO_SEQ";
CREATE SEQUENCE "RUBRO_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "RUBRO_CODIGO_SEQ"
  OWNER TO postgres;



DROP SEQUENCE IF EXISTS "MARCA_CODIGO_SEQ";
CREATE SEQUENCE "MARCA_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "MARCA_CODIGO_SEQ"
  OWNER TO postgres;

DROP SEQUENCE IF EXISTS "VENTA_CODIGO_SEQ";
CREATE SEQUENCE "VENTA_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "VENTA_CODIGO_SEQ"
  OWNER TO postgres;

  DROP SEQUENCE IF EXISTS "TURNO_CODIGO_SEQ";
CREATE SEQUENCE "TURNO_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "TURNO_CODIGO_SEQ"
  OWNER TO postgres;

  DROP SEQUENCE IF EXISTS "TIPO_ID_CODIGO_SEQ";
CREATE SEQUENCE "TIPO_ID_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "TIPO_ID_CODIGO_SEQ"
  OWNER TO postgres;

  
DROP SEQUENCE IF EXISTS "TIPO_GASTOS_CODIGO_SEQ";
CREATE SEQUENCE "TIPO_GASTOS_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "TIPO_GASTOS_CODIGO_SEQ"
  OWNER TO postgres;

  
DROP SEQUENCE IF EXISTS "CONFIG_CODIGO_SEQ";
CREATE SEQUENCE "CONFIG_CODIGO_SEQ"
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE "TIPO_GASTOS_CODIGO_SEQ"
  OWNER TO postgres;

  

  



